### ISSUE TITLE
Video 20 model folder

### ISSUE THREAD

**Issue by newschapmj1** [marcwan/AngularLiveLessons#1]
I am enjoying a well presented video introduction to Angular. I'm completely new to Angular.

I am using Safaribooksonline.com  video 20, 'Create a model for your recipe app'

The editor (in the video) contains a model folder which has recipe.ts
This is not present in my editor.

Is this due a different version of Angular? 
How does the model folder get created?

=============================
My machine details:
Angular 5

"private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by trapeze-bell-peter** [comment]
Same problem for me.  It looks like the first part of the video 20/chapter 3.3 is missing.  We are launched mid-point with an explanation about an extra Typescript feature for defining members within the constructor.  A quick post here on how to create the model directory and file would be helpful - even if it is to say create them by hand.

**Comment by marcwan** [comment]
Hi! This lesson should be added back in now. The editing people seem to have missed it completely. Sorry!!!
