### ISSUE TITLE
EOL08-PART3   EditNewRecipeComponent.html:31 ERROR Error: There is no FormControl instance attached to form control element with name: 'ingredient_0

### ISSUE THREAD

**Issue by ghost** [marcwan/AngularLiveLessons#2]
Error:

EditNewRecipeComponent.html:31 ERROR Error: There is no FormControl instance attached to form control element with name: 'ingredient_0

how to create this error:
click add ingredients button.
click add ingredients button.
click remove the first ingredients button.
fill in the ingredients forms

**Comment by marcwan** [comment]
We've updated this to v3 so this is obsolete.
